apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: kafka-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: api-server
    kind: Deployment
  pollingInterval: 5  # seconds
  cooldownPeriod: 30   # seconds
  minReplicaCount: 1
  maxReplicaCount: 5
  triggers:
    - type: kafka
      metadata:
        bootstrapServers: kafka.default.svc.cluster.local:9092
        consumerGroup: purchase-group
        topic: USER_PURCHASES
        lagThreshold: "1"
        activationLagThreshold: "5"
        # Optional: Specify auth if needed
        # sasl: plain
        # username: user
        # password: password
